default: true

MD013:
  line_length: 500

MD025: false

MD033:
  # Allowed elements
  allowed_elements:
    [
      "a",
      "img",
      "div",
      "grammer-content",
      "ruby",
      "rb",
      "rt",
      "VPTeamMembers",
      "Catalog",
      "script",
      "p",
      "h1",
      "h3",
      "b",
      "br",
      "u",
    ]
